Repository EESSI/software-layer, pull requests merged in 2021-04, with the labels that each got.

#82 fix exit code check for ReFrame and RStudio-Server in software install script
  EESSI-pilot-install-software.sh
Labels: bug

#83 update to ReFrame 3.5.1 + check for missing installations using easystack file
  EESSI-pilot-install-software.sh
  eessi-2021.03.yml
Labels: bug, enhancement

#96 Also add $EPREFIX/bin to $PATH
  init/eessi_environment_variables
Labels: bug, pilot-2021.03
