Repository EESSI/software-layer, pull requests merged in 2024-12, with the labels that each got.

#828 {2023.06}[2023b] GROMACS 2024.4 w/ CUDA 12.4.0
  easystacks/software.eessi.io/2023.06/accel/nvidia/eessi-2023.06-eb-4.9.4-2023b-CUDA.yml
Labels: bot:deploy, 2023.06-software.eessi.io, accel:nvidia

#834 use variable for CVMFS repository in Lmod initialization scripts
  init/lmod/bash
  init/lmod/csh
  init/lmod/fish
  init/lmod/ksh
  init/lmod/zsh
Labels: enhancement, bot:deploy

#835 Use `$EESSI_VERSION` for `EESSI-extend` version and filter Yasm dependency on RISC-V
  EESSI-extend-easybuild.eb
  easystacks/software.eessi.io/2023.06/eessi-2023.06-eb-4.9.1-001-system.yml
  easystacks/software.eessi.io/2023.06/rebuilds/20240506-eb-4.9.1-EESSI-extend-allow-loaded.yml
  easystacks/software.eessi.io/2023.06/rebuilds/20240925-eb-4.9.4-EESSI-extend.yml
  easystacks/software.eessi.io/2023.06/rebuilds/20241008-eb-4.9.4-EESSI-extend.yml
  easystacks/software.eessi.io/2023.06/rebuilds/20241112-eb-4.9.4-EESSI-extend.yml
  easystacks/software.eessi.io/2023.06/rebuilds/20241206-eb-4.9.4-EESSI-extend.yml
  load_eessi_extend_module.sh
Labels: enhancement, bot:deploy

#836 Disable CUDA installation for RISC-V build hosts in `bot/build.sh` (and some other minor enhancements)
  bot/build.sh
Labels: enhancement

#837 Always set `$STORAGE` and `$JOB_STORAGE` in `bot/test.sh`
  bot/test.sh
Labels: enhancement

#838 {2023.06}[foss/2023a] Tombo v1.5.1
  easystacks/software.eessi.io/2023.06/eessi-2023.06-eb-4.9.4-2023a.yml
Labels: bot:deploy, 2023.06-software.eessi.io

#839 {2023.06}[GCC/13.2.0] wxWidgets v3.2.6
  easystacks/software.eessi.io/2023.06/eessi-2023.06-eb-4.9.4-2023b.yml
Labels: bot:deploy, 2023.06-software.eessi.io
